version: '3.8'

services:
  #MYSQL 数据库
  mysql:
    image: mysql:8.0.40
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: lt.123456
      MYSQL_DATABASE: docker_test
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
    # - /home/kyrie/project/docker.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  # Spring Boot 应用
  springboot:
    build: ./springboot  # Spring Boot 项目的路径
    container_name: springboot-container
    #environment:
      #- SPRING_DATASOURCE_URL=jdbc:mysql://192.168.88.3:3306/docker_test
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=lt.123456
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql

  # Vue.js 应用
  vue:
    build: ./vue  # Vue 项目的路径
    container_name: vue-container
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - springboot


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:

